### ISSUE TITLE
Option to hide after several seconds

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [PoziWorld/Scroll-To-Top-Button-extension#1]
This option will allow user to compelete hide the button after several (up to 20) seconds if the page does not scroll at all. This option should not activated by default.

**Comment by PoziWorld** [comment]
Hello @KrasnayaPloshchad,

Thank you for the suggestion.

A few questions for you, if you don't mind:

1. Have you tried setting “Not active button opacity” to “Invisible”?
Looks similar to what you are suggesting with the exception of the button(s) being always hidden unless you mouse over it.
  <a href="https://user-images.githubusercontent.com/5961162/46640255-c7b8c580-cb1f-11e8-8103-42d005107303.png">
    <img
      src="https://user-images.githubusercontent.com/5961162/46640255-c7b8c580-cb1f-11e8-8103-42d005107303.png"
      width="200"
      height="270"
      alt="Scroll To Top Button v7.1.0 * Options > Not active button opacity > Invisible"
      title="Scroll To Top Button v7.1.0 * Options > Not active button opacity > Invisible"
        >
  </a>

2. By saying “if the page does not scroll at all”, do you mean the page is scrollable (can be scrolled) but when there is no scrolling activity on the page (user isn't scrolling the page)?
If so, would it be better to check any user activity on the page: mouse movements and clicks, keyboard presses?

3. By saying “compelete hide the button”, do you mean hide it until user hovers over the area where the button(s) is hidden or until user starts scrolling or even moving his or her mouse?
