### ISSUE TITLE
Store page gone Error 404

### ISSUE THREAD

**Issue by MagicAndre1981** [PoziWorld/Scroll-To-Top-Button-extension#12]
I get a notification about[ 9.1 release](https://github.com/PoziWorld/Scroll-To-Top-Button-extension/releases/tag/v9.1.0), but haven't got it (I'm at 9.0.0 SSV), so I tried to open Chrome Store link, here I get message that the page page is not found.

![image](https://user-images.githubusercontent.com/8274816/73274747-5f936480-41e6-11ea-9c73-3cde708606f1.png)

What is wrong?

**Comment by PoziWorld** [comment]
## Short version
Chrome Web Store now reviews each version for ~one week. Just wait for it.

## Long version
v9.0.0 was uploaded to the Chrome Web Store, Microsoft Store, and Firefox and Opera add-ons catalogues on January 18.
It became available right away for Firefox and Opera. 
A Firefox user reported a bug, and it was fixed and uploaded quickly for Firefox and Opera.

However, these days, the Chrome Web Store takes ~one week to get each version approved and there is no way to upload a new version while one is already in review. 

When v9.0.0 finally became available in the Store, there was no way to stop it from being delivered to users.

In hopes it doesn't make its way to all users, we had to unpublish it, which removed the extension from the Store entirely.

v9.1.0 with the fix has been uploaded to the Store, but it will take ~one week to get approved and bring the extension back to the Store.

Sorry for the inconvenience.

**Comment by PoziWorld** [comment]
@MagicAndre1981, the extension is back in the Store. 
Can you please check?
If the extension hasn't been updated to v9.1.0 yet for you, there is a way to force the update.
You can restart your browser or there is an update button on the extensions page if you enable developer mode.

**Comment by MagicAndre1981** [comment]
Edge has an option to search for updates. I got the 9.1 update and Store link works now again  👍
