### ISSUE TITLE
Some Errors from 9.3.0

### ISSUE THREAD

**Issue by pjpreilly** [PoziWorld/Scroll-To-Top-Button-extension#14]
Have these errors with no known symptoms. Let me know if I should expand any....
![Screenshot 2020-03-06 at 10 23 43 PM](https://user-images.githubusercontent.com/10430084/76135891-540f3680-5ff9-11ea-9445-eb8e4433516c.png)

**Comment by pjpreilly** [comment]
Here the two are expanded:
![Screenshot 2020-03-06 at 10 27 55 PM](https://user-images.githubusercontent.com/10430084/76135941-eadbf300-5ff9-11ea-9b97-9f4583c935cd.png)
![Screenshot 2020-03-06 at 10 27 33 PM](https://user-images.githubusercontent.com/10430084/76135942-f0d1d400-5ff9-11ea-9ef2-a30bfb78ad6a.png)

**Comment by PoziWorld** [comment]
> ![Screenshot 2020-03-06 at 10 27 55 PM](https://user-images.githubusercontent.com/10430084/76135941-eadbf300-5ff9-11ea-9b97-9f4583c935cd.png)

This one has been “muted” (commented-out for now) in v9.4.0.

> ![Screenshot 2020-03-06 at 10 27 33 PM](https://user-images.githubusercontent.com/10430084/76135942-f0d1d400-5ff9-11ea-9ef2-a30bfb78ad6a.png)

This one will keep popping up until Chromium gets native support for all locales the extension is translated into.

**Comment by PoziWorld** [comment]
Will close for now, since a fix for the second one might not come in the near future.

Thank you for the report, @pjpreilly!
