### ISSUE TITLE
Slow Down Scrolling v10.0.3

### ISSUE THREAD

**Issue by pjpreilly** [PoziWorld/Scroll-To-Top-Button-extension#17]
Slow scrolling down with the extension enabled, fine when disabled. Settings reported here....
This only happens occasionally so if you want me to do something when in this state please detail.
[Scroll To Top Button Options.pdf](https://github.com/PoziWorld/Scroll-To-Top-Button-extension/files/6379199/Scroll.To.Top.Button.Options.pdf)

**Comment by PoziWorld** [comment]
Hi @pjpreilly,

Thank you for submitting the issue along with the settings.

Could you please specify how/what do you scroll down with? Mouse? Keyboard?

**Comment by pjpreilly** [comment]
> Hi @pjpreilly,
> 
> Thank you for submitting the issue along with the settings.
> 
> Could you please specify how/what do you scroll down with? Mouse? Keyboard?

2 finger touch-pad on cloudready os on a macbook 4,1

**Comment by PoziWorld** [comment]
No update on this yet.

Thank you for your patience!

**Comment by pjpreilly** [comment]
You need any more info from ME?

**Comment by PoziWorld** [comment]
Not at the moment, thank you.
Will let you know if I do.

**Comment by PoziWorld** [comment]
Hi @pjpreilly,

I think I've finally realized what might be happening in your case:

Your screenshot shows you have “Scroll to top only” from the Expert group of the button modes selected.
Selecting this mode hides the “Scroll down speed” setting, which is likely set to one of the slower options.

Here is what you can try:
1. Go to Options.
2. Select “Flip between top & bottom” or “Dual arrows” from the Expert group.
3. Change “Scroll down speed” to one of the faster options.
4. Select “Scroll to top only” again.
5. Try reproducing the issue.

Please let me know if this doesn't fix it for you. Hope it does.

Sorry it took so long.
