### ISSUE TITLE
Feature request: scroll down continuously

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [PoziWorld/Scroll-To-Top-Button-extension#18]
Hi,

Yours is the first extension I've found that allows adjusting the scroll down speed (thank you for this option!), and currently I have the speed set to 20,000ms in an attempt to find a way to get the extension to work in the way I'm envisioning it as described below.

Quora is one such website where I'd like to be able to use the extension to continuously scroll down until I get to the last "posting." Each time I scroll to the last visible one, it triggers the website to load more. This is tedious when there are hundreds of posts.

Quora is probably a worst case scenario because moving the mouse past the last visible one is what automatically triggers loading the next few. Other websites have a "load more" button that I have to physically click on; it would be nice if my requested feature could handle these, too, but I imagine it would make implementing the request more complicated as the extension would need to know how to detect specific phrases (like "load more").

So for now having it handle sites like Quora would be a big help.

1. For sites like Quora, is there a way your extension can easily detect when it can't scroll anymore and stop executing? Otherwise it would seem like the extension could get caught in an infinite loop, blindly scrolling.

2. The new feature should probably have a way to manually tell the extension to stop scrolling, not only to break out of a potential infinite loop, but also in case I've decided enough has already been loaded and it isn't necessary to do more scrolling.

**Comment by PoziWorld** [comment]
Hello,

Thank you for reaching out, and thank you for your “thank you”! 🙂

This is a very detailed request, and sounds like it would make a great feature!

It's doable, but I will be honest with you:
Lately, I haven't been able to work on this project (extension) much/at all.
I've started a refactoring project to fix one issue in Firefox, but haven't finished it.
Also, to submit an extension update, the extension stores now require a new format of code that might require another refactoring project on my side.

At the moment, I'm not sure if I will continue work on this project in the near future, but if I do this feature is on my to-do list and I will update this GitHub issue if it gets implemented.

Thank you for your support and understanding.

**Comment by PoziWorld** [comment]
Hello @UNIVAC-Colonel-Panic,

Would you be open to “test-drive” this beta version of the extension before it's released to other users?

[Scroll-To-Top-Button-(beta)-v11.1.0-beta.1.zip](https://github.com/PoziWorld/Scroll-To-Top-Button-extension/files/10193062/Scroll-To-Top-Button-.beta.-v11.1.0-beta.1.zip)

_(Here's an article that explains how to install from ZIP – https://dev.to/ben/how-to-install-chrome-extensions-manually-from-github-1612)_

The infinite scrolling has been added to Options, but it's disabled by default.

The trick to disable scrolling is to click the “Scroll down” button while the scrolling is in process.

**Comment by PoziWorld** [comment]
v11.1.0 with the requested feature is now live in the Chrome Web Store:
[Scroll To Top Button on Chrome Web Store](https://chrome.google.com/webstore/detail/scroll-to-top-button/chinfkfmaefdlchhempbfgbdagheknoj)

Thank you for your detailed idea submission, @UNIVAC-Colonel-Panic!
