### ISSUE TITLE
Can the button size increase by 50*100?

### ISSUE THREAD

**Issue by luikhh** [PoziWorld/Scroll-To-Top-Button-extension#2]

**Comment by PoziWorld** [comment]
Hello @luikhh,

Do you mean you want to be able to select a button size of 50 by 100 pixels, like on the mockup below?

![image](https://user-images.githubusercontent.com/5961162/56013275-d20d7500-5ca4-11e9-929b-e9eb293a6ef3.png)

**Comment by luikhh** [comment]
Yes,But I can't find this option.
![无标题](https://user-images.githubusercontent.com/30046009/56049519-3bac8280-5d7c-11e9-86f8-1374317e00cb.png)

**Comment by PoziWorld** [comment]
It doesn't exist yet.
We might want to add an option that would let users set their own preferred size: be it 50x100 or 73x39 or whatever else.

Thank you for your comment.
We'll let you know once it's implemented, but it might take a while.

**Comment by luikhh** [comment]
OK, I am looking forward to it.

**Comment by PoziWorld** [comment]
@luikhh,

If we were to make this a paid feature (being able to set a custom size, such as 50x100, 73x39), would you pay for it?
If so, how much?

Thank you.

**Comment by PoziWorld** [comment]
@luikhh,

It's almost ready.

If you would like to give it a try before it goes live to all users, please temporarily disable the extension and install the [beta version](https://chrome.google.com/webstore/detail/hbidmfhlfagmhnpoeipcanlcokbdmona/) (version 8.0.0-beta-1 should soon become available, after Google will have approved it) of it.

**Comment by PoziWorld** [comment]
@luikhh,

Version 8, which includes the requested functionality, was uploaded to the Chrome Web Store a few hours ago and should become available after Google finishes their review (hoping it won't take longer than 1-2 days).

Please give a try once version 8 is live and let us know.

**Comment by PoziWorld** [comment]
@luikhh,

Thank you for your idea!

Your feedback has been noted:
- https://chrome.google.com/webstore/detail/scroll-to-top-button/chinfkfmaefdlchhempbfgbdagheknoj/
- https://t.me/ScrollToTopButton/23
- https://steemit.com/chrome-extension/@scrolltotopbtn/scroll-to-top-button-v8-0-0-avg
- https://twitter.com/ScrollToTopBtn/status/1185975169015259136
- https://www.facebook.com/ScrollToTopButton/posts/1291312517742663
- https://vk.com/scrolltotopbutton?w=wall-80569939_60
- https://www.ok.ru/group/54802374459420/topic/70212960070428
- https://github.com/PoziWorld/Scroll-To-Top-Button-extension/releases/tag/v8.0.0
- https://github.com/PoziWorld/Scroll-To-Top-Button-extension/blob/master/HISTORY.md#v800
