### ISSUE TITLE
Edge 76 (Chromium) warnings from extension UI

### ISSUE THREAD

**Issue by MagicAndre1981** [PoziWorld/Scroll-To-Top-Button-extension#4]
I have warnings in Edge 76.0.182.9 extension ui for your extension:

`Uncaught (in promise) ReferenceError: punycode is not defined`

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

Any chance to look at it?

**Comment by PoziWorld** [comment]
Hello @MagicAndre1981,

Thank you for getting in touch.

A few questions for you:
1. Do you see that issue on the extension options page?
2. Did you mean version 76.0.182.6?
    Unable to find version 76.0.182.9, the Dev channel seems to be on version 76.0.182.6.
3. Where did you install the extension from? From [Microsoft Store](https://microsoftedge.microsoft.com/insider-addons/category/EdgeExtensions)?

It seems to work fine here in the Dev channel (64-bit v76.0.182.6) and in the Canary channel (64-bit v77.0.193.0).

**Comment by MagicAndre1981** [comment]
I use the Beta Channel and manually get the installer to run it on Windows 8.1 until Microsoft offers it officially to 8.1 users.


```
Microsoft Edge | 76.0.182.9 (Offizielles Build) (64-Bit)
-- | --
Revision | b51b981d83a6efe99b5bc37fd7952814bdd83635
Betriebssystem | Windows 8.1 (Build 9600.19356)
JavaScript | V8 7.6.303.5
Flash | 32.0.0.207 C:\Users\USERNAME\AppData\Local\Microsoft\Edge\Application\76.0.182.9\PepperFlash\pepflashplayer.dll
Benutzer-Agent | Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.25 Safari/537.36 Edg/76.0.182.9
```



I got the extension from MS store page and in extension ui I see the entry Fehler (Error):

![image](https://user-images.githubusercontent.com/8274816/59661647-8a76fe00-91ab-11e9-82ba-165162440f83.png)

Clicking on it shows the 2 warnings I posted

![image](https://user-images.githubusercontent.com/8274816/59661429-176d8780-91ab-11e9-8234-a5c548ad40a3.png)

![image](https://user-images.githubusercontent.com/8274816/59661454-27856700-91ab-11e9-8abe-ffeff80b48d8.png)

The extension itself works so far.

**Comment by PoziWorld** [comment]
@MagicAndre1981,

Thank you for the detailed description and screenshots.


1) `Uncaught (in promise) ReferenceError: punycode is not defined`

    Looks like you have discovered a bug that made it into the [code](https://github.com/PoziWorld/Scroll-To-Top-Button-extension/commit/3147715f1ab73ca6b4b9cd485c73df485713628c#diff-4b1eb3dc48c4e16d49db5b42298fe654) a little bit more than a year ago.

    If you are curious, it's just the order of files that needs to be changed, as one file (tabs.js) tries to access a variable defined in a file that is included later (punycode.min.js).

    Will fix. Thank you for reporting it!

2) `Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

    This is used to load the language files: the extension is available in [multiple languages](https://www.transifex.com/poziworld/scroll-to-top-button/), some of which are not natively supported by Chromium, that's why we have custom code to load the translations.

    Won't fix (for now?), as it would require a lot of refactoring.

**Comment by PoziWorld** [comment]
@MagicAndre1981,

It's almost ready.

If you would like to give it a try before it goes live to all users, please temporarily disable the extension and install the [beta version](https://chrome.google.com/webstore/detail/hbidmfhlfagmhnpoeipcanlcokbdmona/) (version 8.0.0-beta-1 should soon become available, after Google will have approved it) of it.

**Comment by MagicAndre1981** [comment]
ok, I've installed it now in 76.0.182.11 and see no error message in extension UI

**Comment by MagicAndre1981** [comment]
@PoziWorld 

I see the 8 release here on github, but chrome/microsoft edge store shows 7.3. How long will this take to update?

**Comment by PoziWorld** [comment]
@MagicAndre1981,

Version 8 was uploaded to the Chrome Web Store ~7.5 hours ago.
Google has recently started taking some time to review the changes before it allows new versions to go live.

Last few beta versions of the extension (via a separate extension listing) were approved within 1-2 days, so let's hope this one won't take any longer than that.

 
Going to also upload to the Opera add-ons catalog and to the Firefox Add-ons shortly.

Most likely, will not upload to the Microsoft Store for the non-Chromium Edge now, as their tools for preparing the extension have been broken for some time.

**Comment by PoziWorld** [comment]
@MagicAndre1981, v8 is live now.

If you haven't received it yet, you can force-update if you enable the Developer mode on the Extension page in your browser.

**Comment by PoziWorld** [comment]
@MagicAndre1981,

Thank you for your report!

Your feedback has been noted:
- https://chrome.google.com/webstore/detail/scroll-to-top-button/chinfkfmaefdlchhempbfgbdagheknoj/
- https://t.me/ScrollToTopButton/23
- https://steemit.com/chrome-extension/@scrolltotopbtn/scroll-to-top-button-v8-0-0-avg
- https://twitter.com/ScrollToTopBtn/status/1185975169015259136
- https://www.facebook.com/ScrollToTopButton/posts/1291312517742663
- https://vk.com/scrolltotopbutton?w=wall-80569939_60
- https://www.ok.ru/group/54802374459420/topic/70212960070428
- https://github.com/PoziWorld/Scroll-To-Top-Button-extension/releases/tag/v8.0.0
- https://github.com/PoziWorld/Scroll-To-Top-Button-extension/blob/master/HISTORY.md#v800

**Comment by MagicAndre1981** [comment]
I removed the old 7.3 which I've installed from MS Store and installed the 8 from Chrome Store. Now my settings are lost and the dropdown lists are black, so I can't change anything.

**Comment by PoziWorld** [comment]
There have been quite a few issues related to the Options page because it's embedded in chrome://extensions over the years.

This issue doesn't seem to appear when the Options page is displayed in a new tab.

Maybe it's time to make the Options page always open in a new tab.

This should also make it more comfortable to work with it: depending on user's screen size, all settings might be able to fit on the screen at once:
![image](https://user-images.githubusercontent.com/5961162/67642214-b9724e80-f8c6-11e9-8a0b-ec6520e7b26d.png)

**Comment by MagicAndre1981** [comment]
I can't get this to work in a new tab in Edge 78.0.276.20

**Comment by PoziWorld** [comment]
@MagicAndre1981,

Sorry for the confusion, this needs to be implemented on the extension side and will require an update.

Will let you know once it's ready.

**Comment by PoziWorld** [comment]
@MagicAndre1981,

Pushed v8.1.0-rc.1 of the extension. It should become available soon.
Once you receive it, please test it and let us know whether it works for you now.

Thank you for bringing up this issue!

**Comment by MagicAndre1981** [comment]
> Pushed v8.1.0-rc.1 of the extension. It should become available soon.
> Once you receive it, please test it and let us know whether it works for you now.

works fine. I can now configure options again 😍 🙌 👍

**Comment by MagicAndre1981** [comment]
with 8.1.0 AVV (what does this mean?) I get this warning:

`Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.`

![image](https://user-images.githubusercontent.com/8274816/68590507-f6c20900-048e-11ea-936e-5521a1b839cf.png)

**Comment by PoziWorld** [comment]
@MagicAndre1981,

> AVV (what does this mean?)

Initials of a person it's dedicated to.

> `Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.`

Where do you install it from? What browser version?
There should be no _metadata file or directory.

**Comment by MagicAndre1981** [comment]
I still use Edge on Chromium base in version 79 and installed the 8.1 RC last week from Chrome store

**Comment by PoziWorld** [comment]
You had v8.1.0-rc.1 installed and, when your browser tried to auto-update it to v8.1.0 AVV, your browser showed you this exception?

**Comment by MagicAndre1981** [comment]
update is successfuly installed. I just got the notification here on github for the release and checked if I already got the update. Here I notified the entry. I have no idea if it was also there for 8.1 RC, here I made a right click on on the icon on the page and selected "Scroll to Top options"

**Comment by PoziWorld** [comment]
And the extension still works, despite the exception, right?
Just tested new installation from the Chrome Web Store in Edge Beta v79 and Edge Dev v80 – it gets installed successfully, works, and doesn't show any exceptions.

In regards to the exception, there are reports for this error message from a few years ago, and they suggest it's related to the way the Chrome Web Store pushes the updates: it packs the extension resources into a *.crx file and adds a _metadata folder into it. 
But it's strange that a browser built on Chromium would show this message...

**Comment by MagicAndre1981** [comment]
yes, the extension still works. I just tested it here for this page.

**Comment by MagicAndre1981** [comment]
today the error is gone and I only see the 1 known issue with `Synchronous XMLHttpRequest on the main thread`:

![image](https://user-images.githubusercontent.com/8274816/68646487-99c06480-051b-11ea-98c3-f4aa641bafc3.png)

So this was a temporary issue after extension update.
