### ISSUE TITLE
strict_min_version – compatibility with Waterfox Classic

### ISSUE THREAD

**Issue by grahamperrin** [PoziWorld/Scroll-To-Top-Button-extension#7]
Hi

Re: https://redd.it/e4atfn and https://addons.mozilla.org/addon/scroll-to-top-button-extension/versions/

- 7.3.0 is compatible with Waterfox Classic 2019.10
- 8.1.0 and 8.1.1 are not. 

tl;dr historically, Waterfox 56.0 was based on Firefox 56.0.2.

Please update the listings at AMO. 

With or without a fix (for compatibility), please add a `strict_min_version` to the next release. 

Thanks

**Comment by PoziWorld** [comment]
Hi @grahamperrin,

Thank you for the report!

Will look into it and report back.

**Comment by PoziWorld** [comment]
It's related to https://github.com/webcomponents/webcomponentsjs/issues/846.

Looking into how to best resolve it.

**Comment by PoziWorld** [comment]
Still looking into it. 

There are multiple issues stemming from the fact that the extension now uses [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components), specifically [custom elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) and [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM).

Another related issue: https://github.com/mozilla/webextension-polyfill/issues/105

**Comment by PoziWorld** [comment]
Found a very hacky way to make the extension work in Waterfox Classic 2019.10, but it needs a little bit of testing and cleanup before it's shipped.

Will let you know.

**Comment by PoziWorld** [comment]
It seems that Waterfox ignores `strict_min_version` while in the add-on debugging mode.
Wonder whether it will honor the min version when installing from AMO.

Tried `"strict_min_version": "57.0"`, `"strict_min_version": "75.0"` and `"strict_min_version": "2019.12"` in Waterfox Classic 2019.10, but the extension still gets installed, while Firefox 72 does show an error and prevents installation:
![image](https://user-images.githubusercontent.com/5961162/71604320-103e1380-2b16-11ea-82df-370faf03d23d.png)

**Comment by lucknaumann** [comment]
@PoziWorld Thanks for all your work in sleuthing this conundrum. 

> Wonder whether it will honor the min version when installing from AMO.

It should. See [here](https://github.com/rNeomy/auto-tab-discard/issues/118#issuecomment-568931435) and image (same as at link):
![AutoTabDiscard1](https://user-images.githubusercontent.com/51302763/71605614-80a16080-2b27-11ea-8085-031cf3c54b4d.png)

**Comment by PoziWorld** [comment]
@lucknaumann,

> Thanks for all your work in sleuthing this conundrum.

Thank you for your support, feedback, and help!

> It should.

You are right! Waterfox doesn't show the warning/error at `about:debugging#addons`, but it does show it at `about:addons`, apparently.

**Comment by lucknaumann** [comment]
@PoziWorld Glad you got it working! 😃 And you're very welcome! 😊

**Comment by PoziWorld** [comment]
Alright, looks like it works now in Watefox Classic 2019.10:

![image](https://user-images.githubusercontent.com/5961162/71615028-e1e72500-2b63-11ea-9088-6dcf677e1fb0.png)

![image](https://user-images.githubusercontent.com/5961162/71615099-5b7f1300-2b64-11ea-9b8b-86c23b4fcb8c.png)

@grahamperrin, thank you for the report!

@lucknaumann, thank you for your help!

**Comment by lucknaumann** [comment]
@PoziWorld & anyone else who wants to know. 

- Waterfox Classic updated to version 2019.12 a few weeks ago (December 09, 2019).  
- This is the WF version I currently have.
- I had this add-on on hold with version 7.3.0. 
- I let the browser update this add-on today (December 31, 2019) and it's now at version 8.1.2.0 and works perfectly well.

**Comment by PoziWorld** [comment]
@lucknaumann, thank you for getting back with this detailed report! It means a lot.

**Comment by lucknaumann** [comment]
@PoziWorld Thanks for the acknowledgment! It also means a lot! =)
