### ISSUE TITLE
Preferences with Waterfox Classic

### ISSUE THREAD

**Issue by grahamperrin** [PoziWorld/Scroll-To-Top-Button-extension#8]
I prefer instant scrolling etc.. 

Tested at <https://www.mozilla.org/en-US/firefox/72.0beta/releasenotes/>, not effective (scrolling is smooth). 

It may be difficult to make the extension entirely compatible so if you like: 

* close this issue (`wontfix`).

----

Alternatives include legacy [Page Positioning Buttons](https://web.archive.org/web/20171017113625/https://addons.mozilla.org/en-US/firefox/addon/page-positioning-buttons/): 

![image](https://user-images.githubusercontent.com/192271/71630409-bb27fd80-2bfa-11ea-9b3d-7d8ef86903f1.png)

Kind regards

**Comment by PoziWorld** [comment]
@grahamperrin,

> I prefer instant scrolling etc..
> Tested at https://www.mozilla.org/en-US/firefox/72.0beta/releasenotes/, not effective (scrolling is smooth).

Sorry, didn't get it... What exactly are you reporting/saying?

> Alternatives include legacy Page Positioning Buttons

Ha! Interesting idea! Will put it in the to-do list, but it will most likely take a while to implement, as there is a long list of other requests from users and there is very little time to work on them.
But if/when it's implemented, will make sure to let you know and/or tag you.

**Comment by grahamperrin** [comment]
Preferences *appear* to be saved but are not effective.

**Comment by PoziWorld** [comment]
@grahamperrin, just tested in Waterfox Classic 2019.10 and it seems to be working:
New settings apply after the page reload.

Here is a demo – https://streamable.com/tka0j

**Comment by grahamperrin** [comment]
Confirmed working now with Waterfox Classic 2019.12. 

Weird, I'm almost certain that I reloaded pages before opening this issue. 

Apologies for the noise!
