### ISSUE TITLE
Minor extensions conflict with Togglific on Waterfox Classic

### ISSUE THREAD

**Issue by grahamperrin** [PoziWorld/Scroll-To-Top-Button-extension#9]
[Togglific](https://addons.mozilla.org/addon/togglific/)

When: 

* both extensions are enabled
* Scroll To Top Button uses dual arrows
* animation is paused by Togglific

– both buttons point up at sites such as GitHub and (old) Reddit. 

![image](https://user-images.githubusercontent.com/192271/71641787-638c9f00-2c99-11ea-8a5d-8e0fb7ace858.png)

Not reproducible with Firefox Browser 71.0.

**Comment by PoziWorld** [comment]
Thanks for the report. Will look into it.

**Comment by PoziWorld** [comment]
That's related to #7.

Firefox v71 natively [supports](https://caniuse.com/#feat=shadowdomv1) [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM), which allows Scroll To Top Button to hide its button elements and their CSS from the rest of the page, so they are not affected by website's and other extensions' CSS (Togglific injects CSS override rules onto a page).

Will check whether it's easy to override Togglific's overrides.

**Comment by PoziWorld** [comment]
Fixed in v8.1.3, which is now available at https://addons.mozilla.org/addon/scroll-to-top-button-extension/.

Please give it a try.

Thank you for your detailed report!
